apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/G10Twitter/grp10.git
  password: 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
  username: G10Twitter